package com.yhl.rag.agent;

public enum AgentErrorCode {
    UNKNOWN_TOOL,
    VALIDATION_ERROR,
    PERMISSION_DENIED,
    BUSINESS_REJECTED,
    TOOL_EXECUTION_FAILED,
    LLM_CALL_FAILED,
    LLM_OUTPUT_INVALID,
    RAG_NO_CONTEXT,
    CONFIRMATION_REQUIRED,
    CONFIRMATION_EXPIRED,
    AGENT_MAX_STEPS_EXCEEDED,
    AGENT_TIMEOUT,
    DUPLICATE_TOOL_CALL
}
